sources:
  "3.10.0":
    url: "https://www.python.org/ftp/python/3.10.0/Python-3.10.0.tgz"
    sha256: "c4e0cbad57c90690cb813fb4663ef670b4d0f587d8171e2c42bd4c9245bd2758"
  "3.9.18":
    url: "https://www.python.org/ftp/python/3.9.18/Python-3.9.18.tgz"
    sha256: "504ce8cfd59addc04c22f590377c6be454ae7406cb1ebf6f5a350149225a9354"
  "3.8.18":
    url: "https://www.python.org/ftp/python/3.8.18/Python-3.8.18.tgz"
    sha256: "7c5df68bab1be81a52dea0cc2e2705ea00553b67107a301188383d7b57320b16"
  "3.7.12":
    url: "https://www.python.org/ftp/python/3.7.12/Python-3.7.12.tgz"
    sha256: "33b4daaf831be19219659466d12645f87ecec6eb21d4d9f9711018a7b66cce46"
  "2.7.18":
    url: "https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz"
    sha256: "da3080e3b488f648a3d7a4560ddee895284c3380b11d6de75edb986526b9a814"
patches:
  "3.10.0":
    - patch_file: "patches/3.9/3.9.7-0002-_msi-vcxproj.patch"
    - patch_file: "patches/3.10/3.10.0-0003-_ctypes-ffi.patch"
    - patch_file: "patches/3.x-0001-relocatable-python-config.patch"
  "3.9.18":
    - patch_file: "patches/3.9/3.9.7-0002-_msi-vcxproj.patch"
    - patch_file: "patches/3.9/3.9.7-0003-_ctypes-ffi.patch"
    - patch_file: "patches/3.x-0001-relocatable-python-config.patch"
  "3.8.18":
    - patch_file: "patches/3.8/3.8.12-0002-_ctypes-ffi.patch"
    - patch_file: "patches/3.x-0001-relocatable-python-config.patch"
  "3.7.12":
    - patch_file: "patches/3.7/3.7.9-0001-msvc.patch"
    - patch_file: "patches/3.x-0001-relocatable-python-config.patch"
  "2.7.18":
    - patch_file: "patches/2.7/2.7.18-0001-msvc.patch"
    - patch_file: "patches/2.7/2.7.18-0002-add-support-msvc-14.patch"
    - patch_file: "patches/2.7/2.7.18-0003-msvc-fix-static.patch"
